trigger: none 
pool: Default

stages:
  - stage: SoftwareAnalysis
    displayName: Software Component Analysis
    jobs:
      - job: DependencyVulnerabilityScan
        displayName: Dependency Vulnerability Scan(Retire.js)
        steps:
        - task: NodeTool@0
          inputs:
            versionSource: 'spec'
            versionSpec: '18.x'
        - task: PowerShell@2
          displayName: Run Dependency Security Scan
          inputs:
            targetType: 'inline'
            script: |
              npm install -g retire
              retire --outputformat cyclonedx
  - stage: StaticCodeAnalysis
    displayName: Static Code Analysis
    jobs:
      - job: SonarQubeAnalysis
        displayName: Static Code Analysis(SonarQube)
        steps:
        - task: SonarQubePrepare@8
          inputs:
            SonarQube: 'SonarQube'
            scannerMode: 'dotnet'
            projectKey: 'todoproject'
            projectName: 'todoproject'
