trigger: none 
pool: Default

stages:
  - stage: SoftwareAnalysis
    displayName: Software Composition Analysis
    jobs:
      - job: DependencyVulnerabilityScan
        displayName: Dependency Vulnerability Scan(Retire.js)
        
        
